#!/usr/bin/env python

import argparse
import re
import sys


class Atoms:
    atom_nums: "list[int]" = list()
    atom_types: "list[str]" = list()

    def __repr__(self) -> str:
        return f"atom_nums: {self.atom_nums}, atom_types: {self.atom_types}"


class Coefficients:
    norm_const_sum: float = 0.0
    sum_of_mo_coefficient: float = 0.0
    mo_coefficient_list: "list[float]" = list()
    orbital_types: "list[str]" = list()
    atom_list: "list[str]" = list()

    def __repr__(self) -> str:
        return f"norm_const_sum: {self.norm_const_sum}, sum_of_mo_coefficient: {self.sum_of_mo_coefficient}, mo_coefficient_list: {self.mo_coefficient_list}"

    def reset(self):
        self.norm_const_sum = 0.0
        self.sum_of_mo_coefficient = 0.0
        self.mo_coefficient_list: "list[float]" = list()
        self.orbital_types: "list[str]" = list()
        self.atom_list: "list[str]" = list()


class Data_per_orbital_types:
    atom: str = ""
    orbital_type: str = ""
    mo_percentage: float = 0.0

    def __init__(self, atom: str, orbital_type: str, mo_percentage: float) -> None:
        self.atom = atom
        self.orbital_type = orbital_type
        self.mo_percentage = mo_percentage

    def __repr__(self) -> str:
        return f"atom: {self.atom}, orbital_type: {self.orbital_type}, mo_percentage: {self.mo_percentage}"

    def reset(self):
        self.atom = ""
        self.orbital_type = ""
        self.mo_percentage = 0.0


class Data_per_MO:
    mo_info: str = ""
    mo_energy: float = 0.0
    data_per_orbital_types: "list[Data_per_orbital_types]" = list()
    norm_constant: float = 0.0
    sum_coefficients: float = 0.0

    def __init__(self, mo_info: str, mo_energy: float, data_per_orbital_types: "list[Data_per_orbital_types]", norm_constant: float, sum_coefficients: float) -> None:
        self.mo_info = mo_info
        self.mo_energy = mo_energy
        self.data_per_orbital_types = data_per_orbital_types
        self.norm_constant = norm_constant
        self.sum_coefficients = sum_coefficients

    def __repr__(self) -> str:
        return f"mo_info: {self.mo_info}, mo_energy: {self.mo_energy}, coefficients: {self.data_per_orbital_types}"


def parse_args() -> "argparse.Namespace":
    parser = argparse.ArgumentParser(description="Summarize the coefficients from DIRAC output file that *PRIVEC option is used. (c.f. http://www.diracprogram.org/doc/master/manual/analyze/privec.html)")
    parser.add_argument("-f", "--file", type=str, required=True, help="(required) file name of DIRAC output")
    parser.add_argument("-m", "--mol", type=str, required=True, help="(required) molecule specification. Write the molecular formula (e.g. Cu2O). *** DON'T write the rational formula (e.g. CH3OH) ***")
    parser.add_argument("-c", "--compress", action="store_true", help="Compress output. Display all coefficients on one line for each MO. This options is useful when you want to use the result in a spreadsheet like Microsoft Excel.", dest="compress")
    parser.add_argument("-t", "--threshold", type=float, help="threshold. Default: 0.1 %% (e.g) --threshold=0.1 => print orbital with more than 0.1 %% contribution", default=0.1, dest="threshold")
    parser.add_argument("-d", "--decimal", type=int, help="Set the decimal places. Default: 5 (e.g) --decimal=3 => print orbital with 3 decimal places (0.123, 2.456, ...). range: 1-15", default=5, choices=range(1, 16), dest="decimal")
    parser.add_argument("--debug", action="store_true", help="print debug output (Normalization constant, Sum of MO coefficient)", dest="debug")
    parser.add_argument("--no-sort", action="store_true", help="Don't sort the output by MO energy")
    return parser.parse_args()


def is_this_row_for_coefficients(words: "list[str]") -> bool:
    # min: 4 coefficients and other words => 5 words
    if 5 <= len(words) <= 9:
        return True
    else:
        return False


def need_to_skip_this_line(words: "list[str]", is_reading_coefficients: bool) -> bool:
    if is_reading_coefficients and len(words) == 0:
        return False
    elif len(words) <= 1:
        return True
    else:
        return False


def need_to_create_results_for_current_mo(words: "list[str]", is_reading_coefficients: bool) -> bool:
    if is_reading_coefficients and len(words) == 0:
        return True
    else:
        return False


def need_to_get_mo_sym_type(words: "list[str]", is_reading_coefficients: bool) -> bool:
    if not is_reading_coefficients and len(words) == 3 and words[0] == "Fermion" and words[1] == "ircop":
        return True
    return False


def need_to_start_reading_coefficients(words: "list[str]", is_reading_coefficients: bool) -> bool:
    if not is_reading_coefficients and words[1] == "Electronic" and words[2] == "eigenvalue" and "no." in words[3]:
        return True
    return False


def get_dirac_filename(args: "argparse.Namespace") -> str:
    if not args.file:
        sys.exit("ERROR: DIRAC output file is not given. Please use -f option.")
    return args.file


def space_separated_parsing(line: str) -> "list[str]":
    words = re.split(" +", line.rstrip("\n"))
    return [word for word in words if word != ""]


def parse_molecule_input(args: "argparse.Namespace", elements: "list[str]") -> Atoms:
    """
    Nested functions to parse molecule input
    """

    def get_atom_num(num_str: "str | None", elem: str) -> int:
        if num_str is None:
            return 1
        elif num_str not in elem:
            sys.exit(f"ERROR: {num_str} is not in {elem}. Please check the molecule specification (-m or --mol option).")
        return int(num_str)

    def parse_atom(input_list: "list[str]", line: str, atoms: Atoms) -> str:
        letter = "".join(filter(str.isalpha, line)) or None
        if letter not in elements:
            sys.exit(f"ERROR: {line} is invalid.")
        if letter in atoms.atom_types:
            sys.exit(f"ERROR: {letter} is already specified.\n Your input: {input_list}\n Please check the molecule specification (-m or --mol option).")
        return letter

    def parse_atom_num(line: str) -> int:
        num_str = "".join(filter(str.isdigit, line)) or None
        return get_atom_num(num_str, line)

    def create_atoms_data_class(split_list: "list[str]") -> Atoms:
        atoms: Atoms = Atoms()
        for elem in split_list:
            atom_type = parse_atom(split_list, elem, atoms)
            atoms.atom_types.append(atom_type)
            num = parse_atom_num(elem)
            atoms.atom_nums.append(num)
        return atoms

    """
    Main function to parse molecule input
    """
    if not args.mol:
        sys.exit("ERROR: Molecule is not specified. Please use -m or --mol option. (e.g. -m Cu2O)")
    split_per_atom = re.findall("[A-Z][^A-Z]*", args.mol)
    return create_atoms_data_class(split_per_atom)


def get_coefficient(words: "list[str]", atoms: Atoms, coefficients: Coefficients, elements: "list[str]") -> None:
    """
    Nested functions to get coefficient

    words is a list of strings that is split by space.
    words[0] is the number of MO.
    words[1] is the L or S, Large or Small.
    words[2:-5] are symmetry type, Atom and Orbital type.
      Sometimes these elements cannot be separated because there is no space available <--- This is the reason why we use words[2:-5].
    words[-4:] is the coefficient.

    (e.g.)
    sym_and_atom_and_orb_str = "B3gCldyz"
    symmetry_type = "B3g"
    atom_type = "Cl"
    orbital_type = "dyz"
    """

    def get_types() -> "tuple[str, str, str]":

        sym_and_atom_and_orb_str = " ".join(words[2:-4])
        splitted_by_capital = re.findall("[A-Z][^A-Z]*", sym_and_atom_and_orb_str)
        symmetry_type = splitted_by_capital[0].strip()
        # atom_type must be 1 or 2 letters.
        # check splitted_by_capital[1][:2] is not out of range
        if len(splitted_by_capital[1]) >= 2 and splitted_by_capital[1][:2] in elements:  # 2 letters (e.g. Cu)
            atom_type = splitted_by_capital[1][:2]
            orbital_type = splitted_by_capital[1][2:]
        elif splitted_by_capital[1][0] in elements:  # 1 letter (e.g. C)
            atom_type = splitted_by_capital[1][0]
            orbital_type = splitted_by_capital[1][1:]
        else:
            sys.exit(f"ERROR: {splitted_by_capital[1][:1]} is invalid atom type.")

        # orbital_type does not have space or numbers.
        orbital_type = orbital_type.lstrip("0123456789 ")

        # Return symmetry_type, atom_type, orbital_type with no space.
        return symmetry_type.strip(), atom_type.strip(), orbital_type.strip()

    def add_orbital_type(atom_type: str, atom_orb_type: str) -> None:
        if atom_orb_type not in coefficients.orbital_types:
            coefficients.orbital_types.append(atom_orb_type)
            coefficients.atom_list.append(atom_type)
            coefficients.mo_coefficient_list.append(0.0)

    def isfloat(parameter):
        if not parameter.isdecimal():
            try:
                float(parameter)
                return True
            except ValueError:
                return False
        else:
            return False

    def get_coefficient() -> float:
        """
        (e.g)
        words = ["g400", "0.0000278056", "0.0000000000", "0.0000000000", "0.0000000000"]
        """
        alpha1: float = float(words[-4]) if isfloat(words[-4]) else 0.0
        alpha2: float = float(words[-3]) if isfloat(words[-3]) else 0.0
        beta1: float = float(words[-2]) if isfloat(words[-2]) else 0.0
        beta2: float = float(words[-1]) if isfloat(words[-1]) else 0.0
        return alpha1**2 + alpha2**2 + beta1**2 + beta2**2

    def check_atom_type(atom_type: str) -> None:
        if atom_type not in atoms.atom_types:
            print("WARNING: ", atom_type, " is not in the molecule specification. This orbital will be ignored.")
            print(" ".join(atoms.atom_types))
            sys.exit(f"ERROR: atom type {atom_type} is not defined. Please check your -m or --mol option.")

    def add_coefficient(coefficient: float, atom_orb_type: str) -> None:
        magnification = atoms.atom_nums[atoms.atom_types.index(atom_type)]

        coefficient = magnification * coefficient
        coefficients.norm_const_sum += coefficient

        orb_type_idx = coefficients.orbital_types.index(atom_orb_type)
        coefficients.mo_coefficient_list[orb_type_idx] += coefficient

    def parse_words(words: "list[str]") -> "list[str]":
        new_words = []
        # Parses multiple numbers that are sometimes connected without separating them with spaces
        # In DIRAC version <22.0 the number of decimal places is fixed at 10 (decimal_num = 10)
        for word in words:
            num_of_dots = word.count(".")
            if num_of_dots == 0 or num_of_dots == 1:
                new_words.append(word)
            elif num_of_dots >= 2:
                decimal_num = 10
                dotidx = word.find(".")
                while dotidx != -1:
                    word2 = word[: dotidx + decimal_num + 1]
                    new_words.append(word2)
                    word = word[dotidx + decimal_num + 1 :]
                    dotidx = word.find(".")

        return new_words

    """
    Main function to get coefficient
    """
    words = parse_words(words)
    symmetry_type, atom_type, orbital_type = get_types()
    check_atom_type(atom_type)
    coefficient = get_coefficient()
    atom_orb_type = symmetry_type + atom_type + orbital_type

    add_orbital_type(atom_type, atom_orb_type)
    add_coefficient(coefficient, atom_orb_type)

    return None


def create_results_for_current_mo(args: "argparse.Namespace", atoms: Atoms, coefficients: Coefficients) -> "tuple[list[Data_per_orbital_types], float, float]":
    """
    Nested functions to create results for current MO
    """

    def create_data_per_orbital_types():
        data_per_orbital_types: "list[Data_per_orbital_types]" = []
        for (orb, coefficient, atom) in zip(coefficients.orbital_types, coefficients.mo_coefficient_list, coefficients.atom_list):
            atom_num = atoms.atom_nums[atoms.atom_types.index(atom)]
            data = Data_per_orbital_types(atom=atom, orbital_type=orb, mo_percentage=coefficient * 100 / (coefficients.norm_const_sum * atom_num))
            if data.mo_percentage >= args.threshold:
                for _ in range(atom_num):
                    data_per_orbital_types.append(data)
        return data_per_orbital_types

    def calculate_sum_of_mo_coefficient() -> float:
        return (sum([c for c in coefficients.mo_coefficient_list])) / coefficients.norm_const_sum

    """
    Main function to create results for current MO
    """
    data_per_orbital_types = create_data_per_orbital_types()
    data_per_orbital_types.sort(key=lambda x: x.mo_percentage, reverse=True)
    normalization_constant = 0.0
    sum_of_coefficient = 0.0
    if args.debug:
        normalization_constant = coefficients.norm_const_sum
        sum_of_coefficient = calculate_sum_of_mo_coefficient()

    return data_per_orbital_types, normalization_constant, sum_of_coefficient


def check_start_vector_print(words: "list[str]") -> bool:
    # ****************************** Vector print ******************************
    if len(words) < 4:
        return False
    elif words[1] == "Vector" and words[2] == "print":
        return True
    return False


def check_end_vector_print(words: "list[str]") -> bool:
    # ********************** Mulliken population analysis **********************
    if len(words) < 5:
        return False
    elif words[1] == "Mulliken" and words[2] == "population":
        return True
    return False


def write_results(args: "argparse.Namespace", data_all_mo: "list[Data_per_MO]") -> None:
    """
    Write results to stdout
    """
    for mo in data_all_mo:
        print(mo.mo_info, end="" if args.compress else "\n")

        d: Data_per_orbital_types
        for d in mo.data_per_orbital_types:
            if args.compress:
                orb_type = str(d.orbital_type)
                output_str = f" {orb_type} {d.mo_percentage:.{args.decimal}f}"
                print(output_str, end="")
            else:
                orb_type = str(d.orbital_type).ljust(11, " ")
                output_str = f"{orb_type} {d.mo_percentage:{args.decimal+4}.{args.decimal}f} %"
                print(output_str)
        if args.debug:
            print(f"Normalization constant is {mo.norm_constant:.{args.decimal}f}")
            print(f"sum of coefficient {mo.sum_coefficients:.{args.decimal}f}")
        print()


def main() -> None:

    is_reading_coefficients: bool = False
    start_vector_print: bool = False
    electron_number: int = 0
    mo_sym_type: str = ""
    coefficients = Coefficients()
    # fmt: off
    elements: "list[str]" = ["H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg"]
    # fmt: on

    args: "argparse.Namespace" = parse_args()
    dirac_file: str = get_dirac_filename(args)
    atoms: Atoms = parse_molecule_input(args, elements)

    data_all_mo: "list[Data_per_MO]" = []
    with open(dirac_file, encoding="utf-8") as f:
        for line in f:

            words: "list[str]" = space_separated_parsing(line)
            if not start_vector_print:
                if not check_start_vector_print(words):
                    continue
                else:
                    start_vector_print = True

            if start_vector_print and check_end_vector_print(words):
                break

            if need_to_skip_this_line(words, is_reading_coefficients):
                continue

            elif need_to_get_mo_sym_type(words, is_reading_coefficients):
                mo_sym_type = words[2]

            elif need_to_start_reading_coefficients(words, is_reading_coefficients):
                """
                (e.g.)
                words = ["*", "Electronic", "eigenvalue", "no.", "22:", "-2.8417809384721"]
                words = ["*", "Electronic", "eigenvalue", "no.122:", "-2.8417809384721"]
                """
                is_reading_coefficients = True
                electron_number = int(words[-2][:-1].replace("no.", ""))
                mo_energy = float(words[-1])

            elif need_to_create_results_for_current_mo(words, is_reading_coefficients):
                is_reading_coefficients = False
                data, norm_constant, sum_coefficients = create_results_for_current_mo(args, atoms, coefficients)
                if args.compress:
                    info = f"{mo_sym_type} {electron_number} {mo_energy}"
                else:
                    info = f"Electronic no. {electron_number} {mo_sym_type} {mo_energy}"
                data_all_mo.append(Data_per_MO(mo_info=info, mo_energy=mo_energy, data_per_orbital_types=data, norm_constant=norm_constant, sum_coefficients=sum_coefficients))
                # Reset variables
                coefficients.reset()

            elif is_reading_coefficients:
                if not is_this_row_for_coefficients(words):
                    continue
                get_coefficient(words, atoms, coefficients, elements)
    # End of reading file
    if not args.no_sort:
        data_all_mo.sort(key=lambda x: x.mo_energy)
    write_results(args, data_all_mo)


if __name__ == "__main__":
    main()
