name: sum_dirac_dfcoef-deploy

on:
  push:
    tags:
      - v*
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable_test.yml
  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch twine
      - name: Build
        run: hatch build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
