name: sum_dirac_dfcoef-publish

on:
  pull_request:
    types: [closed]

jobs:
  test:
    uses: ./.github/workflows/reusable_test.yml
  publish:
    runs-on: ubuntu-22.04
    # If PR is merged and the tag name starts with 'refs/tags/v' then publish
    if: github.event.pull_request.merged == true && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hatch twine
      - name: Build package
        run: |
          hatch build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
